version: '3.8'

services:
  # ---------------- MINIO ----------------
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio_mc:
    image: minio/mc
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 minioadmin minio123 &&
      mc mb myminio/landing
      "

  # ---------------- POSTGRES AIRFLOW ----------------
  postgres-airflow:
    image: postgres:15
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: post_airflow
      POSTGRES_PASSWORD: airflow_123
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------------- AIRFLOW ----------------
  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow
    restart: always
    depends_on:
      - postgres-airflow
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://post_airflow:airflow_123@postgres-airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOGGING_LEVEL: INFO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minio123
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/config_airflow:/opt/airflow/config_airflow
    command: >
      bash -c "
      sleep 20 &&
      airflow db upgrade &&
      airflow users create \
        --username admin \
        --password admin \
        --firstname admin \
        --lastname admin \
        --role Admin \
        --email admin@email.com || true &&
      airflow webserver & airflow scheduler
      "
  # ---------------- MARIADB ----------------
  mariadb:
    image: mariadb:10
    container_name: local_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: lakeestudo        
      MYSQL_USER: mariadb                 
      MYSQL_PASSWORD: maria123        
    ports:
      - "3306:3306"                      
    volumes:
      - mariadb_data:/var/lib/mysql 

  # ---------------- POSTGRES METABASE ----------------
  postgres-metabase:
    image: postgres:15
    container_name: postgres-metabase
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_metabase_data:/var/lib/postgresql/data

  # ---------------- METABASE ----------------
  metabase:
    image: metabase/metabase:v0.47.1
    container_name: metabase
    depends_on:
      - postgres-metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres-metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data


  spark:
    image: apache/spark:3.5.0
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark_connector:/spark_connector

# ---------------- VOLUMES ----------------
volumes:
  postgres_data:
  minio_data:
  mariadb_data:
  metabase_data:
  postgres_metabase_data: